# created by LocalStack
sudo: required
services:
- docker
script:
- echo $LICENSE_KEY | md5sum; pip install -q localstack; docker pull localstack/localstack; localstack start --docker
  & sleep 20
- pip install -q awscli-local; awslocal kinesis list-streams
