# created by LocalStack
sudo: required
services:
- docker
script:
- pip install -q localstack; docker pull localstack/localstack; localstack start --docker
  & sleep 20
- pip install -q awscli-local
- awslocal kinesis list-streams
- awslocal cognito-idp create-user-pool --pool-name p1
- export AWS_ACCESS_KEY_ID=foobar AWS_SECRET_ACCESS_KEY=foobar AWS_DEFAULT_REGION=us-east-1
- aws --no-verify-ssl kinesis list-streams
