# created by LocalStack
sudo: required
services:
- docker
script:
- pip install -q localstack; docker pull localstack/localstack; localstack start --docker
  & sleep 10
- pip install -q awscli-local; awslocal kinesis list-streams
